
title: "Oodles of Doodles"
tagline: "learning with us about doodles"
email: piperdoodle143@gmail.com
description: >-
  A blog about our adventures with our labradoodles
author: Piperdoodle
url: "https://www.oodlesofdoodles.blog"
baseurl: "/"
google_analytics: G-VYSLJ0Y564

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: assets/css
